# Generated by Django 3.0.5 on 2021-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
